source 'git@git.elenet.me:lingyu.zhou/ZLYSpecs.git'
platform :ios, ‘8.0’

target 'NewProject' do
  use_frameworks!
  
  pod 'Lotusoot','~>0.0.3'
  pod 'TestAccountModule','~>0.0.3'
  pod 'ModulePublic','~>0.0.3'
  
  target 'NewProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
